# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dcs/dcs.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dcs/dcs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dcs.atmosphere.v0 import atmosphere_pb2 as dcs_dot_atmosphere_dot_v0_dot_atmosphere__pb2
from dcs.coalition.v0 import coalition_pb2 as dcs_dot_coalition_dot_v0_dot_coalition__pb2
from dcs.common.v0 import common_pb2 as dcs_dot_common_dot_v0_dot_common__pb2
from dcs.controller.v0 import controller_pb2 as dcs_dot_controller_dot_v0_dot_controller__pb2
from dcs.custom.v0 import custom_pb2 as dcs_dot_custom_dot_v0_dot_custom__pb2
from dcs.group.v0 import group_pb2 as dcs_dot_group_dot_v0_dot_group__pb2
from dcs.hook.v0 import hook_pb2 as dcs_dot_hook_dot_v0_dot_hook__pb2
from dcs.metadata.v0 import metadata_pb2 as dcs_dot_metadata_dot_v0_dot_metadata__pb2
from dcs.mission.v0 import mission_pb2 as dcs_dot_mission_dot_v0_dot_mission__pb2
from dcs.net.v0 import net_pb2 as dcs_dot_net_dot_v0_dot_net__pb2
from dcs.srs.v0 import srs_pb2 as dcs_dot_srs_dot_v0_dot_srs__pb2
from dcs.timer.v0 import timer_pb2 as dcs_dot_timer_dot_v0_dot_timer__pb2
from dcs.trigger.v0 import trigger_pb2 as dcs_dot_trigger_dot_v0_dot_trigger__pb2
from dcs.unit.v0 import unit_pb2 as dcs_dot_unit_dot_v0_dot_unit__pb2
from dcs.world.v0 import world_pb2 as dcs_dot_world_dot_v0_dot_world__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdcs/dcs.proto\x12\x03\x64\x63s\x1a\"dcs/atmosphere/v0/atmosphere.proto\x1a dcs/coalition/v0/coalition.proto\x1a\x1a\x64\x63s/common/v0/common.proto\x1a\"dcs/controller/v0/controller.proto\x1a\x1a\x64\x63s/custom/v0/custom.proto\x1a\x18\x64\x63s/group/v0/group.proto\x1a\x16\x64\x63s/hook/v0/hook.proto\x1a\x1e\x64\x63s/metadata/v0/metadata.proto\x1a\x1c\x64\x63s/mission/v0/mission.proto\x1a\x14\x64\x63s/net/v0/net.proto\x1a\x14\x64\x63s/srs/v0/srs.proto\x1a\x18\x64\x63s/timer/v0/timer.proto\x1a\x1c\x64\x63s/trigger/v0/trigger.proto\x1a\x16\x64\x63s/unit/v0/unit.proto\x1a\x18\x64\x63s/world/v0/world.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.dcs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
