# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dcs/metadata/v0/metadata.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dcs/metadata/v0/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64\x63s/metadata/v0/metadata.proto\x12\x0f\x64\x63s.metadata.v0\"\x12\n\x10GetHealthRequest\"\"\n\x11GetHealthResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\"\x13\n\x11GetVersionRequest\"%\n\x12GetVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t2\xc0\x01\n\x0fMetadataService\x12T\n\tGetHealth\x12!.dcs.metadata.v0.GetHealthRequest\x1a\".dcs.metadata.v0.GetHealthResponse\"\x00\x12W\n\nGetVersion\x12\".dcs.metadata.v0.GetVersionRequest\x1a#.dcs.metadata.v0.GetVersionResponse\"\x00\x42UZ/github.com/DCS-gRPC/go-bindings/dcs/v0/metadata\xaa\x02!RurouniJones.Dcs.Grpc.V0.Metadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.metadata.v0.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/DCS-gRPC/go-bindings/dcs/v0/metadata\252\002!RurouniJones.Dcs.Grpc.V0.Metadata'
  _globals['_GETHEALTHREQUEST']._serialized_start=51
  _globals['_GETHEALTHREQUEST']._serialized_end=69
  _globals['_GETHEALTHRESPONSE']._serialized_start=71
  _globals['_GETHEALTHRESPONSE']._serialized_end=105
  _globals['_GETVERSIONREQUEST']._serialized_start=107
  _globals['_GETVERSIONREQUEST']._serialized_end=126
  _globals['_GETVERSIONRESPONSE']._serialized_start=128
  _globals['_GETVERSIONRESPONSE']._serialized_end=165
  _globals['_METADATASERVICE']._serialized_start=168
  _globals['_METADATASERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
