# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dcs.metadata.v0 import metadata_pb2 as dcs_dot_metadata_dot_v0_dot_metadata__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dcs/metadata/v0/metadata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetadataServiceStub:
    """A service to get administrative/meta data like server health checks and version
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/dcs.metadata.v0.MetadataService/GetHealth',
                request_serializer=dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetHealthRequest.SerializeToString,
                response_deserializer=dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetHealthResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/dcs.metadata.v0.MetadataService/GetVersion',
                request_serializer=dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetVersionResponse.FromString,
                _registered_method=True)


class MetadataServiceServicer:
    """A service to get administrative/meta data like server health checks and version
    """

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetHealthRequest.FromString,
                    response_serializer=dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetHealthResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetVersionRequest.FromString,
                    response_serializer=dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.metadata.v0.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcs.metadata.v0.MetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataService:
    """A service to get administrative/meta data like server health checks and version
    """

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.metadata.v0.MetadataService/GetHealth',
            dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetHealthRequest.SerializeToString,
            dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.metadata.v0.MetadataService/GetVersion',
            dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetVersionRequest.SerializeToString,
            dcs_dot_metadata_dot_v0_dot_metadata__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
