# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dcs.coalition.v0 import coalition_pb2 as dcs_dot_coalition_dot_v0_dot_coalition__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dcs/coalition/v0/coalition_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoalitionServiceStub:
    """https://wiki.hoggitworld.com/view/DCS_singleton_coalition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddGroup = channel.unary_unary(
                '/dcs.coalition.v0.CoalitionService/AddGroup',
                request_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddGroupRequest.SerializeToString,
                response_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddGroupResponse.FromString,
                _registered_method=True)
        self.GetStaticObjects = channel.unary_unary(
                '/dcs.coalition.v0.CoalitionService/GetStaticObjects',
                request_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetStaticObjectsRequest.SerializeToString,
                response_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetStaticObjectsResponse.FromString,
                _registered_method=True)
        self.AddStaticObject = channel.unary_unary(
                '/dcs.coalition.v0.CoalitionService/AddStaticObject',
                request_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddStaticObjectRequest.SerializeToString,
                response_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddStaticObjectResponse.FromString,
                _registered_method=True)
        self.AddLinkedStatic = channel.unary_unary(
                '/dcs.coalition.v0.CoalitionService/AddLinkedStatic',
                request_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddLinkedStaticRequest.SerializeToString,
                response_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddLinkedStaticResponse.FromString,
                _registered_method=True)
        self.GetGroups = channel.unary_unary(
                '/dcs.coalition.v0.CoalitionService/GetGroups',
                request_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetGroupsRequest.SerializeToString,
                response_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetGroupsResponse.FromString,
                _registered_method=True)
        self.GetBullseye = channel.unary_unary(
                '/dcs.coalition.v0.CoalitionService/GetBullseye',
                request_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetBullseyeRequest.SerializeToString,
                response_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetBullseyeResponse.FromString,
                _registered_method=True)
        self.GetPlayerUnits = channel.unary_unary(
                '/dcs.coalition.v0.CoalitionService/GetPlayerUnits',
                request_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetPlayerUnitsRequest.SerializeToString,
                response_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetPlayerUnitsResponse.FromString,
                _registered_method=True)


class CoalitionServiceServicer:
    """https://wiki.hoggitworld.com/view/DCS_singleton_coalition
    """

    def AddGroup(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_addGroup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStaticObjects(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getStaticObjects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStaticObject(self, request, context):
        """Focussed on statics (linked statics - see `AddLinkedStatic`)
        https://wiki.hoggitworld.com/view/DCS_func_addStaticObject
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLinkedStatic(self, request, context):
        """Focussed on properties relevant to linked static objects
        https://wiki.hoggitworld.com/view/DCS_func_addStaticObject
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroups(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getGroups
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBullseye(self, request, context):
        """
        Get the Bullseye for the coalition

        This position is set at mission start and does not change for the duration
        of the mission.

        See https://wiki.hoggitworld.com/view/DCS_func_getMainRefPoint for more
        details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlayerUnits(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getPlayers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoalitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGroup,
                    request_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddGroupRequest.FromString,
                    response_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddGroupResponse.SerializeToString,
            ),
            'GetStaticObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStaticObjects,
                    request_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetStaticObjectsRequest.FromString,
                    response_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetStaticObjectsResponse.SerializeToString,
            ),
            'AddStaticObject': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStaticObject,
                    request_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddStaticObjectRequest.FromString,
                    response_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddStaticObjectResponse.SerializeToString,
            ),
            'AddLinkedStatic': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLinkedStatic,
                    request_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddLinkedStaticRequest.FromString,
                    response_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddLinkedStaticResponse.SerializeToString,
            ),
            'GetGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroups,
                    request_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetGroupsRequest.FromString,
                    response_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetGroupsResponse.SerializeToString,
            ),
            'GetBullseye': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBullseye,
                    request_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetBullseyeRequest.FromString,
                    response_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetBullseyeResponse.SerializeToString,
            ),
            'GetPlayerUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerUnits,
                    request_deserializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetPlayerUnitsRequest.FromString,
                    response_serializer=dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetPlayerUnitsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.coalition.v0.CoalitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcs.coalition.v0.CoalitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoalitionService:
    """https://wiki.hoggitworld.com/view/DCS_singleton_coalition
    """

    @staticmethod
    def AddGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.coalition.v0.CoalitionService/AddGroup',
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddGroupRequest.SerializeToString,
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStaticObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.coalition.v0.CoalitionService/GetStaticObjects',
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetStaticObjectsRequest.SerializeToString,
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetStaticObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStaticObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.coalition.v0.CoalitionService/AddStaticObject',
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddStaticObjectRequest.SerializeToString,
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddStaticObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLinkedStatic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.coalition.v0.CoalitionService/AddLinkedStatic',
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddLinkedStaticRequest.SerializeToString,
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.AddLinkedStaticResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.coalition.v0.CoalitionService/GetGroups',
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetGroupsRequest.SerializeToString,
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBullseye(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.coalition.v0.CoalitionService/GetBullseye',
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetBullseyeRequest.SerializeToString,
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetBullseyeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlayerUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.coalition.v0.CoalitionService/GetPlayerUnits',
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetPlayerUnitsRequest.SerializeToString,
            dcs_dot_coalition_dot_v0_dot_coalition__pb2.GetPlayerUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
