# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dcs.group.v0 import group_pb2 as dcs_dot_group_dot_v0_dot_group__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dcs/group/v0/group_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroupServiceStub:
    """https://wiki.hoggitworld.com/view/DCS_Class_Group
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUnits = channel.unary_unary(
                '/dcs.group.v0.GroupService/GetUnits',
                request_serializer=dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsRequest.SerializeToString,
                response_deserializer=dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsResponse.FromString,
                _registered_method=True)
        self.Activate = channel.unary_unary(
                '/dcs.group.v0.GroupService/Activate',
                request_serializer=dcs_dot_group_dot_v0_dot_group__pb2.ActivateRequest.SerializeToString,
                response_deserializer=dcs_dot_group_dot_v0_dot_group__pb2.ActivateResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/dcs.group.v0.GroupService/Destroy',
                request_serializer=dcs_dot_group_dot_v0_dot_group__pb2.DestroyRequest.SerializeToString,
                response_deserializer=dcs_dot_group_dot_v0_dot_group__pb2.DestroyResponse.FromString,
                _registered_method=True)


class GroupServiceServicer:
    """https://wiki.hoggitworld.com/view/DCS_Class_Group
    """

    def GetUnits(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getUnits
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Activate(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_activate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_destroy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnits,
                    request_deserializer=dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsRequest.FromString,
                    response_serializer=dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsResponse.SerializeToString,
            ),
            'Activate': grpc.unary_unary_rpc_method_handler(
                    servicer.Activate,
                    request_deserializer=dcs_dot_group_dot_v0_dot_group__pb2.ActivateRequest.FromString,
                    response_serializer=dcs_dot_group_dot_v0_dot_group__pb2.ActivateResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=dcs_dot_group_dot_v0_dot_group__pb2.DestroyRequest.FromString,
                    response_serializer=dcs_dot_group_dot_v0_dot_group__pb2.DestroyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.group.v0.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcs.group.v0.GroupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupService:
    """https://wiki.hoggitworld.com/view/DCS_Class_Group
    """

    @staticmethod
    def GetUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.group.v0.GroupService/GetUnits',
            dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsRequest.SerializeToString,
            dcs_dot_group_dot_v0_dot_group__pb2.GetUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Activate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.group.v0.GroupService/Activate',
            dcs_dot_group_dot_v0_dot_group__pb2.ActivateRequest.SerializeToString,
            dcs_dot_group_dot_v0_dot_group__pb2.ActivateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.group.v0.GroupService/Destroy',
            dcs_dot_group_dot_v0_dot_group__pb2.DestroyRequest.SerializeToString,
            dcs_dot_group_dot_v0_dot_group__pb2.DestroyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
