# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dcs.world.v0 import world_pb2 as dcs_dot_world_dot_v0_dot_world__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dcs/world/v0/world_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorldServiceStub:
    """https://wiki.hoggitworld.com/view/DCS_singleton_world
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAirbases = channel.unary_unary(
                '/dcs.world.v0.WorldService/GetAirbases',
                request_serializer=dcs_dot_world_dot_v0_dot_world__pb2.GetAirbasesRequest.SerializeToString,
                response_deserializer=dcs_dot_world_dot_v0_dot_world__pb2.GetAirbasesResponse.FromString,
                _registered_method=True)
        self.GetMarkPanels = channel.unary_unary(
                '/dcs.world.v0.WorldService/GetMarkPanels',
                request_serializer=dcs_dot_world_dot_v0_dot_world__pb2.GetMarkPanelsRequest.SerializeToString,
                response_deserializer=dcs_dot_world_dot_v0_dot_world__pb2.GetMarkPanelsResponse.FromString,
                _registered_method=True)
        self.GetTheatre = channel.unary_unary(
                '/dcs.world.v0.WorldService/GetTheatre',
                request_serializer=dcs_dot_world_dot_v0_dot_world__pb2.GetTheatreRequest.SerializeToString,
                response_deserializer=dcs_dot_world_dot_v0_dot_world__pb2.GetTheatreResponse.FromString,
                _registered_method=True)
        self.SearchObjects = channel.unary_unary(
                '/dcs.world.v0.WorldService/SearchObjects',
                request_serializer=dcs_dot_world_dot_v0_dot_world__pb2.SearchObjectsRequest.SerializeToString,
                response_deserializer=dcs_dot_world_dot_v0_dot_world__pb2.SearchObjectsResponse.FromString,
                _registered_method=True)


class WorldServiceServicer:
    """https://wiki.hoggitworld.com/view/DCS_singleton_world
    """

    def GetAirbases(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getAirbases
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarkPanels(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getMarkPanels
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTheatre(self, request, context):
        """Returns the theatre (Map name) of the mission
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchObjects(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_searchObjects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorldServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAirbases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAirbases,
                    request_deserializer=dcs_dot_world_dot_v0_dot_world__pb2.GetAirbasesRequest.FromString,
                    response_serializer=dcs_dot_world_dot_v0_dot_world__pb2.GetAirbasesResponse.SerializeToString,
            ),
            'GetMarkPanels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarkPanels,
                    request_deserializer=dcs_dot_world_dot_v0_dot_world__pb2.GetMarkPanelsRequest.FromString,
                    response_serializer=dcs_dot_world_dot_v0_dot_world__pb2.GetMarkPanelsResponse.SerializeToString,
            ),
            'GetTheatre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTheatre,
                    request_deserializer=dcs_dot_world_dot_v0_dot_world__pb2.GetTheatreRequest.FromString,
                    response_serializer=dcs_dot_world_dot_v0_dot_world__pb2.GetTheatreResponse.SerializeToString,
            ),
            'SearchObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchObjects,
                    request_deserializer=dcs_dot_world_dot_v0_dot_world__pb2.SearchObjectsRequest.FromString,
                    response_serializer=dcs_dot_world_dot_v0_dot_world__pb2.SearchObjectsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.world.v0.WorldService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcs.world.v0.WorldService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorldService:
    """https://wiki.hoggitworld.com/view/DCS_singleton_world
    """

    @staticmethod
    def GetAirbases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.world.v0.WorldService/GetAirbases',
            dcs_dot_world_dot_v0_dot_world__pb2.GetAirbasesRequest.SerializeToString,
            dcs_dot_world_dot_v0_dot_world__pb2.GetAirbasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarkPanels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.world.v0.WorldService/GetMarkPanels',
            dcs_dot_world_dot_v0_dot_world__pb2.GetMarkPanelsRequest.SerializeToString,
            dcs_dot_world_dot_v0_dot_world__pb2.GetMarkPanelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTheatre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.world.v0.WorldService/GetTheatre',
            dcs_dot_world_dot_v0_dot_world__pb2.GetTheatreRequest.SerializeToString,
            dcs_dot_world_dot_v0_dot_world__pb2.GetTheatreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.world.v0.WorldService/SearchObjects',
            dcs_dot_world_dot_v0_dot_world__pb2.SearchObjectsRequest.SerializeToString,
            dcs_dot_world_dot_v0_dot_world__pb2.SearchObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
