# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dcs.timer.v0 import timer_pb2 as dcs_dot_timer_dot_v0_dot_timer__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dcs/timer/v0/timer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TimerServiceStub:
    """https://wiki.hoggitworld.com/view/DCS_singleton_timer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/dcs.timer.v0.TimerService/GetTime',
                request_serializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeRequest.SerializeToString,
                response_deserializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeResponse.FromString,
                _registered_method=True)
        self.GetAbsoluteTime = channel.unary_unary(
                '/dcs.timer.v0.TimerService/GetAbsoluteTime',
                request_serializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetAbsoluteTimeRequest.SerializeToString,
                response_deserializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetAbsoluteTimeResponse.FromString,
                _registered_method=True)
        self.GetTimeZero = channel.unary_unary(
                '/dcs.timer.v0.TimerService/GetTimeZero',
                request_serializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeZeroRequest.SerializeToString,
                response_deserializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeZeroResponse.FromString,
                _registered_method=True)


class TimerServiceServicer:
    """https://wiki.hoggitworld.com/view/DCS_singleton_timer
    """

    def GetTime(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getTime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAbsoluteTime(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getAbsTime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeZero(self, request, context):
        """https://wiki.hoggitworld.com/view/DCS_func_getTime0
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeRequest.FromString,
                    response_serializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeResponse.SerializeToString,
            ),
            'GetAbsoluteTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAbsoluteTime,
                    request_deserializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetAbsoluteTimeRequest.FromString,
                    response_serializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetAbsoluteTimeResponse.SerializeToString,
            ),
            'GetTimeZero': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeZero,
                    request_deserializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeZeroRequest.FromString,
                    response_serializer=dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeZeroResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.timer.v0.TimerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcs.timer.v0.TimerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TimerService:
    """https://wiki.hoggitworld.com/view/DCS_singleton_timer
    """

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.timer.v0.TimerService/GetTime',
            dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeRequest.SerializeToString,
            dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAbsoluteTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.timer.v0.TimerService/GetAbsoluteTime',
            dcs_dot_timer_dot_v0_dot_timer__pb2.GetAbsoluteTimeRequest.SerializeToString,
            dcs_dot_timer_dot_v0_dot_timer__pb2.GetAbsoluteTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeZero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.timer.v0.TimerService/GetTimeZero',
            dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeZeroRequest.SerializeToString,
            dcs_dot_timer_dot_v0_dot_timer__pb2.GetTimeZeroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
