# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dcs/srs/v0/srs.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dcs/srs/v0/srs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dcs.common.v0 import common_pb2 as dcs_dot_common_dot_v0_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x63s/srs/v0/srs.proto\x12\ndcs.srs.v0\x1a\x1a\x64\x63s/common/v0/common.proto\"\xed\x04\n\x0fTransmitRequest\x12\x0c\n\x04ssml\x18\x01 \x01(\t\x12\x16\n\tplaintext\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\tfrequency\x18\x03 \x01(\x04\x12\x1c\n\x0fsrs_client_name\x18\x04 \x01(\tH\x02\x88\x01\x01\x12.\n\x08position\x18\x05 \x01(\x0b\x32\x1c.dcs.common.v0.InputPosition\x12+\n\tcoalition\x18\x06 \x01(\x0e\x32\x18.dcs.common.v0.Coalition\x12\r\n\x05\x61sync\x18\x07 \x01(\x08\x12.\n\x03\x61ws\x18\x08 \x01(\x0b\x32\x1f.dcs.srs.v0.TransmitRequest.AwsH\x00\x12\x32\n\x05\x61zure\x18\t \x01(\x0b\x32!.dcs.srs.v0.TransmitRequest.AzureH\x00\x12\x34\n\x06gcloud\x18\n \x01(\x0b\x32\".dcs.srs.v0.TransmitRequest.GCloudH\x00\x12\x32\n\x03win\x18\x0b \x01(\x0b\x32#.dcs.srs.v0.TransmitRequest.WindowsH\x00\x1a#\n\x03\x41ws\x12\x12\n\x05voice\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_voice\x1a%\n\x05\x41zure\x12\x12\n\x05voice\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_voice\x1a&\n\x06GCloud\x12\x12\n\x05voice\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_voice\x1a\'\n\x07Windows\x12\x12\n\x05voice\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_voiceB\n\n\x08providerB\x0c\n\n_plaintextB\x12\n\x10_srs_client_name\"\'\n\x10TransmitResponse\x12\x13\n\x0b\x64uration_ms\x18\x01 \x01(\r\"\x13\n\x11GetClientsRequest\"\x8e\x01\n\x12GetClientsResponse\x12\x36\n\x07\x63lients\x18\x01 \x03(\x0b\x32%.dcs.srs.v0.GetClientsResponse.Client\x1a@\n\x06\x43lient\x12!\n\x04unit\x18\x01 \x01(\x0b\x32\x13.dcs.common.v0.Unit\x12\x13\n\x0b\x66requencies\x18\x02 \x03(\x04\x32\xa4\x01\n\nSrsService\x12G\n\x08Transmit\x12\x1b.dcs.srs.v0.TransmitRequest\x1a\x1c.dcs.srs.v0.TransmitResponse\"\x00\x12M\n\nGetClients\x12\x1d.dcs.srs.v0.GetClientsRequest\x1a\x1e.dcs.srs.v0.GetClientsResponse\"\x00\x42KZ*github.com/DCS-gRPC/go-bindings/dcs/v0/srs\xaa\x02\x1cRurouniJones.Dcs.Grpc.V0.Srsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.srs.v0.srs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/DCS-gRPC/go-bindings/dcs/v0/srs\252\002\034RurouniJones.Dcs.Grpc.V0.Srs'
  _globals['_TRANSMITREQUEST']._serialized_start=65
  _globals['_TRANSMITREQUEST']._serialized_end=686
  _globals['_TRANSMITREQUEST_AWS']._serialized_start=485
  _globals['_TRANSMITREQUEST_AWS']._serialized_end=520
  _globals['_TRANSMITREQUEST_AZURE']._serialized_start=522
  _globals['_TRANSMITREQUEST_AZURE']._serialized_end=559
  _globals['_TRANSMITREQUEST_GCLOUD']._serialized_start=561
  _globals['_TRANSMITREQUEST_GCLOUD']._serialized_end=599
  _globals['_TRANSMITREQUEST_WINDOWS']._serialized_start=601
  _globals['_TRANSMITREQUEST_WINDOWS']._serialized_end=640
  _globals['_TRANSMITRESPONSE']._serialized_start=688
  _globals['_TRANSMITRESPONSE']._serialized_end=727
  _globals['_GETCLIENTSREQUEST']._serialized_start=729
  _globals['_GETCLIENTSREQUEST']._serialized_end=748
  _globals['_GETCLIENTSRESPONSE']._serialized_start=751
  _globals['_GETCLIENTSRESPONSE']._serialized_end=893
  _globals['_GETCLIENTSRESPONSE_CLIENT']._serialized_start=829
  _globals['_GETCLIENTSRESPONSE_CLIENT']._serialized_end=893
  _globals['_SRSSERVICE']._serialized_start=896
  _globals['_SRSSERVICE']._serialized_end=1060
# @@protoc_insertion_point(module_scope)
