# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dcs/timer/v0/timer.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dcs/timer/v0/timer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x63s/timer/v0/timer.proto\x12\x0c\x64\x63s.timer.v0\"\x10\n\x0eGetTimeRequest\"\x1f\n\x0fGetTimeResponse\x12\x0c\n\x04time\x18\x01 \x01(\x01\"\x18\n\x16GetAbsoluteTimeRequest\"Q\n\x17GetAbsoluteTimeResponse\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\r\x12\r\n\x05month\x18\x03 \x01(\r\x12\x0c\n\x04year\x18\x04 \x01(\x05\"\x14\n\x12GetTimeZeroRequest\"M\n\x13GetTimeZeroResponse\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\r\x12\r\n\x05month\x18\x03 \x01(\r\x12\x0c\n\x04year\x18\x04 \x01(\x05\x32\x90\x02\n\x0cTimerService\x12H\n\x07GetTime\x12\x1c.dcs.timer.v0.GetTimeRequest\x1a\x1d.dcs.timer.v0.GetTimeResponse\"\x00\x12`\n\x0fGetAbsoluteTime\x12$.dcs.timer.v0.GetAbsoluteTimeRequest\x1a%.dcs.timer.v0.GetAbsoluteTimeResponse\"\x00\x12T\n\x0bGetTimeZero\x12 .dcs.timer.v0.GetTimeZeroRequest\x1a!.dcs.timer.v0.GetTimeZeroResponse\"\x00\x42OZ,github.com/DCS-gRPC/go-bindings/dcs/v0/timer\xaa\x02\x1eRurouniJones.Dcs.Grpc.V0.Timerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.timer.v0.timer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/DCS-gRPC/go-bindings/dcs/v0/timer\252\002\036RurouniJones.Dcs.Grpc.V0.Timer'
  _globals['_GETTIMEREQUEST']._serialized_start=42
  _globals['_GETTIMEREQUEST']._serialized_end=58
  _globals['_GETTIMERESPONSE']._serialized_start=60
  _globals['_GETTIMERESPONSE']._serialized_end=91
  _globals['_GETABSOLUTETIMEREQUEST']._serialized_start=93
  _globals['_GETABSOLUTETIMEREQUEST']._serialized_end=117
  _globals['_GETABSOLUTETIMERESPONSE']._serialized_start=119
  _globals['_GETABSOLUTETIMERESPONSE']._serialized_end=200
  _globals['_GETTIMEZEROREQUEST']._serialized_start=202
  _globals['_GETTIMEZEROREQUEST']._serialized_end=222
  _globals['_GETTIMEZERORESPONSE']._serialized_start=224
  _globals['_GETTIMEZERORESPONSE']._serialized_end=301
  _globals['_TIMERSERVICE']._serialized_start=304
  _globals['_TIMERSERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
