-- Kobuleti has controllers and no sky -- and then the whole table stopped being
-- anybody's to hand-write.
--
-- `sectors` held three rows, written into 005 by hand: batumi-approach,
-- batumi-tower, georgia-center. 005's own comment named the day it would break:
--
--     "...the moment a second aerodrome exists, and a second aerodrome is the
--      next test."
--
-- It exists. 008 COALESCEs onto the unbounded sector, so an aeroplane inside no
-- described volume is GEORGIA CENTER'S -- and nobody had claimed Kobuleti, so a
-- jet three miles off its runway at two thousand feet was handed to Center
-- while still in the circuit. Found by `tools/ghost_flight.py` on its first run.
--
-- THE ROW WAS NOT WRONG; IT WAS ABSENT, and absence read as an answer. That is
-- the failure mode a hand-maintained table has, and this file originally fixed
-- it the obvious way: two more hand-written polygons. Which answers the wrong
-- question --
--
--     "So how do we prevent missing airspace bug going forward. We're going to
--      add dozens of airfields"
--
-- -- because you cannot, by hand, and not for want of effort. `sectors` was a
-- SECOND COPY of a fact the theatre already holds: where the aerodromes are and
-- who works them. Maintained independently of its source, it drifts, and the
-- drift is invisible until somebody flies it. See docs/STATE.md.
--
-- So the volumes are DERIVED now -- `core.airspace.sectors_for` -- and pushed at
-- startup by the bridge, exactly as the fix catalogue is and for the identical
-- reason: the bridge knows which map is loaded and this container does not. The
-- push REPLACES the table, so a Nevada run cannot leave Batumi's airspace lying
-- over the wrong desert. An aerodrome gets airspace by EXISTING.
--
-- What is left here is therefore nothing. The rows this file used to insert are
-- the push's to write, and a migration that also wrote them would be the second
-- writer all over again. It stays as a numbered no-op because migrations are
-- replayable history and renumbering applied files is worse than an empty one,
-- and because the reasoning above is the reason the next person will want.
--
-- A fresh database has no sectors until a bridge starts. That is correct and it
-- is the same bargain as the fix table: with no bridge there is no controller,
-- and `set_sectors` refuses an empty push precisely so a bridge that cannot
-- build the list leaves the last good airspace alone rather than wiping it.

SELECT 1;
