# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dcs/net/v0/net.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dcs/net/v0/net.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dcs.common.v0 import common_pb2 as dcs_dot_common_dot_v0_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x63s/net/v0/net.proto\x12\ndcs.net.v0\x1a\x1a\x64\x63s/common/v0/common.proto\">\n\x11SendChatToRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x18\n\x10target_player_id\x18\x02 \x01(\r\"\x14\n\x12SendChatToResponse\"O\n\x0fSendChatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12+\n\tcoalition\x18\x02 \x01(\x0e\x32\x18.dcs.common.v0.Coalition\"\x12\n\x10SendChatResponse\"\x13\n\x11GetPlayersRequest\"\xfe\x01\n\x12GetPlayersResponse\x12=\n\x07players\x18\x01 \x03(\x0b\x32,.dcs.net.v0.GetPlayersResponse.GetPlayerInfo\x1a\xa8\x01\n\rGetPlayerInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12+\n\tcoalition\x18\x03 \x01(\x0e\x32\x18.dcs.common.v0.Coalition\x12\x0c\n\x04slot\x18\x04 \x01(\t\x12\x0c\n\x04ping\x18\x05 \x01(\r\x12\x16\n\x0eremote_address\x18\x06 \x01(\t\x12\x0c\n\x04ucid\x18\x07 \x01(\t\x12\x0e\n\x06locale\x18\x08 \x01(\t\"i\n\x16\x46orcePlayerSlotRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\r\x12+\n\tcoalition\x18\x02 \x01(\x0e\x32\x18.dcs.common.v0.Coalition\x12\x0f\n\x07slot_id\x18\x03 \x01(\t\"\x19\n\x17\x46orcePlayerSlotResponse\"0\n\x11KickPlayerRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12KickPlayerResponse2\xa0\x03\n\nNetService\x12M\n\nSendChatTo\x12\x1d.dcs.net.v0.SendChatToRequest\x1a\x1e.dcs.net.v0.SendChatToResponse\"\x00\x12G\n\x08SendChat\x12\x1b.dcs.net.v0.SendChatRequest\x1a\x1c.dcs.net.v0.SendChatResponse\"\x00\x12M\n\nGetPlayers\x12\x1d.dcs.net.v0.GetPlayersRequest\x1a\x1e.dcs.net.v0.GetPlayersResponse\"\x00\x12M\n\nKickPlayer\x12\x1d.dcs.net.v0.KickPlayerRequest\x1a\x1e.dcs.net.v0.KickPlayerResponse\"\x00\x12\\\n\x0f\x46orcePlayerSlot\x12\".dcs.net.v0.ForcePlayerSlotRequest\x1a#.dcs.net.v0.ForcePlayerSlotResponse\"\x00\x42KZ*github.com/DCS-gRPC/go-bindings/dcs/v0/net\xaa\x02\x1cRurouniJones.Dcs.Grpc.V0.Netb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.net.v0.net_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/DCS-gRPC/go-bindings/dcs/v0/net\252\002\034RurouniJones.Dcs.Grpc.V0.Net'
  _globals['_SENDCHATTOREQUEST']._serialized_start=64
  _globals['_SENDCHATTOREQUEST']._serialized_end=126
  _globals['_SENDCHATTORESPONSE']._serialized_start=128
  _globals['_SENDCHATTORESPONSE']._serialized_end=148
  _globals['_SENDCHATREQUEST']._serialized_start=150
  _globals['_SENDCHATREQUEST']._serialized_end=229
  _globals['_SENDCHATRESPONSE']._serialized_start=231
  _globals['_SENDCHATRESPONSE']._serialized_end=249
  _globals['_GETPLAYERSREQUEST']._serialized_start=251
  _globals['_GETPLAYERSREQUEST']._serialized_end=270
  _globals['_GETPLAYERSRESPONSE']._serialized_start=273
  _globals['_GETPLAYERSRESPONSE']._serialized_end=527
  _globals['_GETPLAYERSRESPONSE_GETPLAYERINFO']._serialized_start=359
  _globals['_GETPLAYERSRESPONSE_GETPLAYERINFO']._serialized_end=527
  _globals['_FORCEPLAYERSLOTREQUEST']._serialized_start=529
  _globals['_FORCEPLAYERSLOTREQUEST']._serialized_end=634
  _globals['_FORCEPLAYERSLOTRESPONSE']._serialized_start=636
  _globals['_FORCEPLAYERSLOTRESPONSE']._serialized_end=661
  _globals['_KICKPLAYERREQUEST']._serialized_start=663
  _globals['_KICKPLAYERREQUEST']._serialized_end=711
  _globals['_KICKPLAYERRESPONSE']._serialized_start=713
  _globals['_KICKPLAYERRESPONSE']._serialized_end=733
  _globals['_NETSERVICE']._serialized_start=736
  _globals['_NETSERVICE']._serialized_end=1152
# @@protoc_insertion_point(module_scope)
