# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dcs.srs.v0 import srs_pb2 as dcs_dot_srs_dot_v0_dot_srs__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dcs/srs/v0/srs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SrsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transmit = channel.unary_unary(
                '/dcs.srs.v0.SrsService/Transmit',
                request_serializer=dcs_dot_srs_dot_v0_dot_srs__pb2.TransmitRequest.SerializeToString,
                response_deserializer=dcs_dot_srs_dot_v0_dot_srs__pb2.TransmitResponse.FromString,
                _registered_method=True)
        self.GetClients = channel.unary_unary(
                '/dcs.srs.v0.SrsService/GetClients',
                request_serializer=dcs_dot_srs_dot_v0_dot_srs__pb2.GetClientsRequest.SerializeToString,
                response_deserializer=dcs_dot_srs_dot_v0_dot_srs__pb2.GetClientsResponse.FromString,
                _registered_method=True)


class SrsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Transmit(self, request, context):
        """Synthesize text to speech and transmit it over SRS. By default, this blocks until a
        transmission completed (unless `async` is set to `true`). This can be used to prevent
        transmission to overlap each other, by not sending another transmission on the same frequency
        until you've received the response from the previous transmission on that frequency. However,
        it does not block or prevent any other client from transmitting over the same frequency at the
        same time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClients(self, request, context):
        """Retrieve a list of units (players) and their active frequencies that are connected to SRS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SrsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transmit': grpc.unary_unary_rpc_method_handler(
                    servicer.Transmit,
                    request_deserializer=dcs_dot_srs_dot_v0_dot_srs__pb2.TransmitRequest.FromString,
                    response_serializer=dcs_dot_srs_dot_v0_dot_srs__pb2.TransmitResponse.SerializeToString,
            ),
            'GetClients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClients,
                    request_deserializer=dcs_dot_srs_dot_v0_dot_srs__pb2.GetClientsRequest.FromString,
                    response_serializer=dcs_dot_srs_dot_v0_dot_srs__pb2.GetClientsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.srs.v0.SrsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcs.srs.v0.SrsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SrsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transmit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.srs.v0.SrsService/Transmit',
            dcs_dot_srs_dot_v0_dot_srs__pb2.TransmitRequest.SerializeToString,
            dcs_dot_srs_dot_v0_dot_srs__pb2.TransmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.srs.v0.SrsService/GetClients',
            dcs_dot_srs_dot_v0_dot_srs__pb2.GetClientsRequest.SerializeToString,
            dcs_dot_srs_dot_v0_dot_srs__pb2.GetClientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
