# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dcs/controller/v0/controller.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dcs/controller/v0/controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dcs.common.v0 import common_pb2 as dcs_dot_common_dot_v0_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"dcs/controller/v0/controller.proto\x12\x11\x64\x63s.controller.v0\x1a\x1a\x64\x63s/common/v0/common.proto\"\xff\x01\n\x14SetAlarmStateRequest\x12\x14\n\ngroup_name\x18\x01 \x01(\tH\x00\x12\x13\n\tunit_name\x18\x02 \x01(\tH\x00\x12G\n\x0b\x61larm_state\x18\x03 \x01(\x0e\x32\x32.dcs.controller.v0.SetAlarmStateRequest.AlarmState\"k\n\nAlarmState\x12\x1b\n\x17\x41LARM_STATE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41LARM_STATE_AUTO\x10\x01\x12\x15\n\x11\x41LARM_STATE_GREEN\x10\x02\x12\x13\n\x0f\x41LARM_STATE_RED\x10\x03\x42\x06\n\x04name\"\x17\n\x15SetAlarmStateResponse\"\x96\x03\n\x19GetDetectedTargetsRequest\x12\x11\n\tunit_name\x18\x01 \x01(\t\x12\x1b\n\x0einclude_object\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12W\n\x0e\x64\x65tection_type\x18\x03 \x01(\x0e\x32:.dcs.controller.v0.GetDetectedTargetsRequest.DetectionTypeH\x01\x88\x01\x01\"\xc9\x01\n\rDetectionType\x12\x1e\n\x1a\x44\x45TECTION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15\x44\x45TECTION_TYPE_VISUAL\x10\x01\x12\x18\n\x14\x44\x45TECTION_TYPE_OPTIC\x10\x02\x12\x18\n\x14\x44\x45TECTION_TYPE_RADAR\x10\x04\x12\x17\n\x13\x44\x45TECTION_TYPE_IRST\x10\x08\x12\x16\n\x12\x44\x45TECTION_TYPE_RWR\x10\x10\x12\x18\n\x14\x44\x45TECTION_TYPE_DLINK\x10 B\x11\n\x0f_include_objectB\x11\n\x0f_detection_type\"F\n\x1aGetDetectedTargetsResponse\x12(\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x16.dcs.common.v0.Contact2\xee\x01\n\x11\x43ontrollerService\x12\x64\n\rSetAlarmState\x12\'.dcs.controller.v0.SetAlarmStateRequest\x1a(.dcs.controller.v0.SetAlarmStateResponse\"\x00\x12s\n\x12GetDetectedTargets\x12,.dcs.controller.v0.GetDetectedTargetsRequest\x1a-.dcs.controller.v0.GetDetectedTargetsResponse\"\x00\x42YZ1github.com/DCS-gRPC/go-bindings/dcs/v0/controller\xaa\x02#RurouniJones.Dcs.Grpc.V0.Controllerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.controller.v0.controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/DCS-gRPC/go-bindings/dcs/v0/controller\252\002#RurouniJones.Dcs.Grpc.V0.Controller'
  _globals['_SETALARMSTATEREQUEST']._serialized_start=86
  _globals['_SETALARMSTATEREQUEST']._serialized_end=341
  _globals['_SETALARMSTATEREQUEST_ALARMSTATE']._serialized_start=226
  _globals['_SETALARMSTATEREQUEST_ALARMSTATE']._serialized_end=333
  _globals['_SETALARMSTATERESPONSE']._serialized_start=343
  _globals['_SETALARMSTATERESPONSE']._serialized_end=366
  _globals['_GETDETECTEDTARGETSREQUEST']._serialized_start=369
  _globals['_GETDETECTEDTARGETSREQUEST']._serialized_end=775
  _globals['_GETDETECTEDTARGETSREQUEST_DETECTIONTYPE']._serialized_start=536
  _globals['_GETDETECTEDTARGETSREQUEST_DETECTIONTYPE']._serialized_end=737
  _globals['_GETDETECTEDTARGETSRESPONSE']._serialized_start=777
  _globals['_GETDETECTEDTARGETSRESPONSE']._serialized_end=847
  _globals['_CONTROLLERSERVICE']._serialized_start=850
  _globals['_CONTROLLERSERVICE']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
