"""Build a throwaway mission that measures terrain height around an airfield.

Approach and holding design needs real minimum safe altitudes. DCS only exposes
terrain height from inside a running mission, and pydcs carries no elevation
data, so the cheapest path is: load this, wait a few seconds, quit, and parse
the numbers back out of dcs.log.

  uv run python build_survey.py            # Batumi, 25 nm, 1 nm grid
  uv run python build_survey.py Kutaisi 30
"""

import shutil
import sys
import zipfile
from pathlib import Path

from dcs.action import DoScriptFile
from dcs.mission import Mission, StartType
from dcs.mapping import Point
from dcs.planes import P_51D_30_NA
from dcs.task import CAP
from dcs.terrain import Caucasus
from dcs.triggers import TriggerStart

HERE = Path(__file__).parent
OUT = config.MISSION_OUT / "Terrain-Survey.miz"
from marshall import config
MISSIONS = config.DCS_MISSIONS

FIELDS = {
    "Batumi": (-355811, 617386),
    "Kobuleti": (-317962, 635633),
    "Kutaisi": (-284887, 683859),
    "Senaki-Kolkhi": (-281782, 647279),
}


def build(field: str, radius_nm: float, step_nm: float) -> Mission:
    x, z = FIELDS[field]
    m = Mission(terrain=Caucasus())
    m.set_sortie_text(f"Terrain Survey - {field}")

    # A client has to exist for the mission to be loadable, but nothing is flown.
    # Park it well out to sea so it cannot hit anything while the survey runs.
    flight = m.flight_group(
        country=m.country("USA"), name="Survey", aircraft_type=P_51D_30_NA,
        airport=None, position=Point(x, z - 40 * 1852, m.terrain),
        altitude=3000, speed=110, maintask=CAP, start_type=StartType.Runway,
        group_size=1)
    flight.frequency = 124
    for unit in flight.units:
        unit.set_client()
    for point in flight.points:
        point.alt, point.speed = 3000, 110

    # Config must be prepended into the script FILE, not passed as DoScript text.
    # getValueDictByKey returns the key name rather than the text at run time, so
    # DCS tries to compile "DictKey_Translation_5" as a chunk and dies with
    # "'=' expected near '<eof>'". Everything goes through a resource file.
    generated = HERE / "_generated_survey.lua"
    generated.write_text(
        "-- GENERATED by build_survey.py -- edit survey.lua instead.\n"
        f"SURVEY_CENTRE = {{x = {x}, z = {z}}}\n"
        f"SURVEY_RADIUS_NM = {radius_nm}\n"
        f"SURVEY_STEP_NM = {step_nm}\n\n"
        + (HERE / "survey.lua").read_text(encoding="utf-8"),
        encoding="utf-8")

    trig = TriggerStart(comment=f"survey {field}")
    trig.add_action(DoScriptFile(
        m.map_resource.add_resource_file(str(generated))))
    m.triggerrules.triggers.append(trig)
    return m


if __name__ == "__main__":
    field = sys.argv[1] if len(sys.argv) > 1 else "Batumi"
    radius = float(sys.argv[2]) if len(sys.argv) > 2 else 25
    step = float(sys.argv[3]) if len(sys.argv) > 3 else 1

    mission = build(field, radius, step)
    mission.save(str(OUT))

    # pydcs omits the theatre marker the ME always writes.
    with zipfile.ZipFile(OUT) as zf:
        blobs = {n: zf.read(n) for n in zf.namelist()}
    blobs.setdefault("theatre", b"Caucasus")
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as zf:
        for n, data in blobs.items():
            zf.writestr(n, data)

    dest = MISSIONS / OUT.name
    if dest.exists():
        dest.unlink()
    shutil.copy2(OUT, dest)
    if dest.stat().st_size != OUT.stat().st_size:
        raise SystemExit("DEPLOY FAILED - close the Mission Editor")

    side = int(2 * radius / step) + 1
    print(f"built {OUT.name} -> {dest}")
    print(f"  {field}: {radius:.0f} nm radius, {step:.1f} nm grid "
          f"({side}x{side} = {side*side} samples)")
    print("  Load it, wait for 'Survey complete', quit. Then:")
    print("  uv run python read_survey.py")
