# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dcs.custom.v0 import custom_pb2 as dcs_dot_custom_dot_v0_dot_custom__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dcs/custom/v0/custom_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomServiceStub:
    """The Custom service is for APIs that do not map to the "standard library" of
    DCS APIs provided by Eagle Dynamics.

    Expect to find APIs here that may be useful for mission frameworks etc.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestMissionAssignment = channel.unary_unary(
                '/dcs.custom.v0.CustomService/RequestMissionAssignment',
                request_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.RequestMissionAssignmentRequest.SerializeToString,
                response_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.RequestMissionAssignmentResponse.FromString,
                _registered_method=True)
        self.JoinMission = channel.unary_unary(
                '/dcs.custom.v0.CustomService/JoinMission',
                request_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.JoinMissionRequest.SerializeToString,
                response_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.JoinMissionResponse.FromString,
                _registered_method=True)
        self.AbortMission = channel.unary_unary(
                '/dcs.custom.v0.CustomService/AbortMission',
                request_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.AbortMissionRequest.SerializeToString,
                response_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.AbortMissionResponse.FromString,
                _registered_method=True)
        self.GetMissionStatus = channel.unary_unary(
                '/dcs.custom.v0.CustomService/GetMissionStatus',
                request_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.GetMissionStatusRequest.SerializeToString,
                response_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.GetMissionStatusResponse.FromString,
                _registered_method=True)
        self.Eval = channel.unary_unary(
                '/dcs.custom.v0.CustomService/Eval',
                request_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.EvalRequest.SerializeToString,
                response_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.EvalResponse.FromString,
                _registered_method=True)
        self.GetMagneticDeclination = channel.unary_unary(
                '/dcs.custom.v0.CustomService/GetMagneticDeclination',
                request_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.GetMagneticDeclinationRequest.SerializeToString,
                response_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.GetMagneticDeclinationResponse.FromString,
                _registered_method=True)


class CustomServiceServicer:
    """The Custom service is for APIs that do not map to the "standard library" of
    DCS APIs provided by Eagle Dynamics.

    Expect to find APIs here that may be useful for mission frameworks etc.
    """

    def RequestMissionAssignment(self, request, context):
        """DCT Function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinMission(self, request, context):
        """DCT Function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortMission(self, request, context):
        """DCT Function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMissionStatus(self, request, context):
        """DCT Function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Eval(self, request, context):
        """Evaluate some Lua inside of the mission and return the result as a JSON
        string. Disabled by default.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMagneticDeclination(self, request, context):
        """*
        Calculates the magnetic declination at the given position using the
        International Geomagnetic Reference Field (IGRF) model. The result is not
        always exactly the same as what DCS seem to use, but it is very close (DCS
        doesn't expose its declination).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestMissionAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMissionAssignment,
                    request_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.RequestMissionAssignmentRequest.FromString,
                    response_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.RequestMissionAssignmentResponse.SerializeToString,
            ),
            'JoinMission': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinMission,
                    request_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.JoinMissionRequest.FromString,
                    response_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.JoinMissionResponse.SerializeToString,
            ),
            'AbortMission': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortMission,
                    request_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.AbortMissionRequest.FromString,
                    response_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.AbortMissionResponse.SerializeToString,
            ),
            'GetMissionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMissionStatus,
                    request_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.GetMissionStatusRequest.FromString,
                    response_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.GetMissionStatusResponse.SerializeToString,
            ),
            'Eval': grpc.unary_unary_rpc_method_handler(
                    servicer.Eval,
                    request_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.EvalRequest.FromString,
                    response_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.EvalResponse.SerializeToString,
            ),
            'GetMagneticDeclination': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMagneticDeclination,
                    request_deserializer=dcs_dot_custom_dot_v0_dot_custom__pb2.GetMagneticDeclinationRequest.FromString,
                    response_serializer=dcs_dot_custom_dot_v0_dot_custom__pb2.GetMagneticDeclinationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcs.custom.v0.CustomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcs.custom.v0.CustomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomService:
    """The Custom service is for APIs that do not map to the "standard library" of
    DCS APIs provided by Eagle Dynamics.

    Expect to find APIs here that may be useful for mission frameworks etc.
    """

    @staticmethod
    def RequestMissionAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.custom.v0.CustomService/RequestMissionAssignment',
            dcs_dot_custom_dot_v0_dot_custom__pb2.RequestMissionAssignmentRequest.SerializeToString,
            dcs_dot_custom_dot_v0_dot_custom__pb2.RequestMissionAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.custom.v0.CustomService/JoinMission',
            dcs_dot_custom_dot_v0_dot_custom__pb2.JoinMissionRequest.SerializeToString,
            dcs_dot_custom_dot_v0_dot_custom__pb2.JoinMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.custom.v0.CustomService/AbortMission',
            dcs_dot_custom_dot_v0_dot_custom__pb2.AbortMissionRequest.SerializeToString,
            dcs_dot_custom_dot_v0_dot_custom__pb2.AbortMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMissionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.custom.v0.CustomService/GetMissionStatus',
            dcs_dot_custom_dot_v0_dot_custom__pb2.GetMissionStatusRequest.SerializeToString,
            dcs_dot_custom_dot_v0_dot_custom__pb2.GetMissionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Eval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.custom.v0.CustomService/Eval',
            dcs_dot_custom_dot_v0_dot_custom__pb2.EvalRequest.SerializeToString,
            dcs_dot_custom_dot_v0_dot_custom__pb2.EvalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMagneticDeclination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcs.custom.v0.CustomService/GetMagneticDeclination',
            dcs_dot_custom_dot_v0_dot_custom__pb2.GetMagneticDeclinationRequest.SerializeToString,
            dcs_dot_custom_dot_v0_dot_custom__pb2.GetMagneticDeclinationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
