# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dcs/group/v0/group.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dcs/group/v0/group.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dcs.common.v0 import common_pb2 as dcs_dot_common_dot_v0_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x63s/group/v0/group.proto\x12\x0c\x64\x63s.group.v0\x1a\x1a\x64\x63s/common/v0/common.proto\"E\n\x0fGetUnitsRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\x13\n\x06\x61\x63tive\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\t\n\x07_active\"6\n\x10GetUnitsResponse\x12\"\n\x05units\x18\x01 \x03(\x0b\x32\x13.dcs.common.v0.Unit\"%\n\x0f\x41\x63tivateRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\"\x12\n\x10\x41\x63tivateResponse\"$\n\x0e\x44\x65stroyRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\"\x11\n\x0f\x44\x65stroyResponse2\xf2\x01\n\x0cGroupService\x12K\n\x08GetUnits\x12\x1d.dcs.group.v0.GetUnitsRequest\x1a\x1e.dcs.group.v0.GetUnitsResponse\"\x00\x12K\n\x08\x41\x63tivate\x12\x1d.dcs.group.v0.ActivateRequest\x1a\x1e.dcs.group.v0.ActivateResponse\"\x00\x12H\n\x07\x44\x65stroy\x12\x1c.dcs.group.v0.DestroyRequest\x1a\x1d.dcs.group.v0.DestroyResponse\"\x00\x42OZ,github.com/DCS-gRPC/go-bindings/dcs/v0/group\xaa\x02\x1eRurouniJones.Dcs.Grpc.V0.Groupb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcs.group.v0.group_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/DCS-gRPC/go-bindings/dcs/v0/group\252\002\036RurouniJones.Dcs.Grpc.V0.Group'
  _globals['_GETUNITSREQUEST']._serialized_start=70
  _globals['_GETUNITSREQUEST']._serialized_end=139
  _globals['_GETUNITSRESPONSE']._serialized_start=141
  _globals['_GETUNITSRESPONSE']._serialized_end=195
  _globals['_ACTIVATEREQUEST']._serialized_start=197
  _globals['_ACTIVATEREQUEST']._serialized_end=234
  _globals['_ACTIVATERESPONSE']._serialized_start=236
  _globals['_ACTIVATERESPONSE']._serialized_end=254
  _globals['_DESTROYREQUEST']._serialized_start=256
  _globals['_DESTROYREQUEST']._serialized_end=292
  _globals['_DESTROYRESPONSE']._serialized_start=294
  _globals['_DESTROYRESPONSE']._serialized_end=311
  _globals['_GROUPSERVICE']._serialized_start=314
  _globals['_GROUPSERVICE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
